development:
  adapter: postgresql
  encoding: unicode
  database: teaser_development
  pool: 5
  username: stephan.hagemann
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: teaser_test
  pool: 5
  username: stephan.hagemann
  password:
